### PR TITLE
Added alternate version configuration option.

### PR DESCRIPTION
**Pull request by odrotbohm**
There's a pretty brilliant Never Gonna Give You Up cover by Scary Pockets available on YouTube [0]. The commit adds a new configuration property rickroll.version which defaults to the original video URL but allows to also set it to "scary-pockets" to rather redirect to the other version.

[0] https://www.youtube.com/watch?v=sQnoZUR6fvY

### CODE REVIEW

**Comment by TomCools** [comment]
**Thank you for your contribution to this project!**

Normally I'd complain about this being a slippery slope into a hardcoded list of RickRoll URLs and that it would be better to make the URL itself configurable. But you know what:
image

Add a small note of the added configuration in the README please and i'll push a release later today.

**Comment by odrotbohm** [comment]
> … that it would be better to make the URL itself configurable.

I think one can make a point that it should be in the hand of the project owner / maintainer to bless proper rickroll URLs ☝️😬. 

> Add a small note of the added configuration in the README please and i'll push a release later today.

Do you want me to tweak the PR or are you gonna do that yourself?

**Comment by TomCools** [comment]
I got some time today. I'll do it myself for this time ;-). Thanks for your contribution. I'll post it on Twitter and such when a new release is ready for the world to use. 
Thank you for actually using this thing in your German Corona app. funny to see the "Used By" labels in Github for this one. <3

**Comment by odrotbohm** [comment]
Ze Germanz take security serious. Thanks, Tom! 🙇

**Pull request merged**
